import { Providers } from "@/app/providers"

export const metadata = {
  title: 'Loja',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
      <Providers>
      {children}
      </Providers>
      </ body>
    </html>
  )
}
